sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev;
    fi

