sudo: true
language: rust
script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
addons:
  apt:
    packages:
      - libssl-dev
#cache: cargo

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev;
    fi
