os: Visual Studio 2015
environment:
    global:
        PROJECT_NAME: tetris
        RUSTUP_INIT_SKIP_MSVC_CHECK: 1
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

test_script:
    - cargo test --release --verbose --no-default-features headless && cargo build --release

build: false

cache:
    - C:\Users\appveyor\.cargo\registry

artifacts:
    - path: target\release\tetris.exe

