[window_mode]
width = 1280.0
height = 720.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
min_width = 0.0
min_height = 0.0
max_width = 0.0
max_height = 0.0
resizable = true

[window_setup]
title = "Tetris"
samples = "Zero"
vsync = false
icon = ""
srgb = true

[backend]
type = "OpenGL"
major = 3
minor = 2

[modules]
gamepad = true
audio = true
